BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBB

BBBBB BBBBB
   gettext(u'Server Error')  FFFFFFFFFFFF
BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBB
  XXXXX
    XXXX gettext(u'Server Error')  FFFFFFFFFFFFXXXXX
  XXXXXX
BBBBBBBB
