BBBB BBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BB BBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X X
            XXXX XX
        XX
    XXXXXXXXX
    BBBBBBBBBBBBB BBBBBBBBBBB BBBB
  BBBBB
BBBBBBB
