BBBB BBBB
BBBB BBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
      XXXX
      XXXXX XXXXXXXXXXXXXXXXBBBBBBB BBBBBBBBB BBBBBBBBBBBBBXXXXXXX
    XXXXX
  XXXXXXXXX
XXXXXX
