BBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
	BBBBBBBBBBBBB BBBBBBBBBBBBBB BBBB
    BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
        BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFFFFFF FFFFFFX
            XXXXX XXX
					XXX
        XXXXXXXXX
        BBBBBBBB
    BBBBB
BBBBBBBB
