BBBB BBBB
BBBB BBBB


XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXXXX gettext(u'Management View')   FFFFFFFFFFFFXXXXXXXX
XXXXXXX
XXXXXX
BB BBBBBBBB
  XXX XXXXXXXXXXXXXXXXX
    BBB BBBBBBB BB BBBBBBBB
      XXXBB BBBBBBBBBBBB XXXXXXXXBBBBBXXXXXX
    BBBBBB
  XXXXX
BBBBB
XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXX
  BBBBBBBBBB
  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Clear cache')  FFFFFFFFFFFFXX
XXXXXXX
XXXXXXX
XXXXXXX
