BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBB
BBBB BBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB

BBBBB BBBBB
   gettext(u'{program_name} Record') 
  BBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
   FFFFFFFFFFFF
BBBBBBBB BBBBB

BBBBB BBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
  BBBBBBBBBBBBB BBBBBBBBBB BBBB
    BB BBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBB
    BBBB
      BBBBB BBBBBBBBBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXXXXXXXFFFFFFFFXXX
            XXXXXXXXX FFFFFFFFFFFFFFFFFFX
            XXXXX XXX
            XXXXXXXX XXX
          XXX
        XXXXXXXXX
    BBBBBBBB
    BBBBB
BBBBBBBB
