BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBB
BBBB BBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB

BBBBB BBBBB
   FFFFFFFFFFFF
BBBBBBBB BBBBB

BBBBB BBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
  BBBBBBBBBBBBB BBBBBBBBB BBBB
    BB BBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBB
    BBBB
      BBBBB BBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX X
          XXXXXX XXX
          XXXXXXXXX XXXXXXXXXXXXFFFFFFFFXXX
          XXXXXXXXXXXX XXX
          XXXXXXXX XXX
          XXXXXXXXXXX XXX
        XXX
        XXXXXXXXX
      BBBBBBBB
    BBBBB
BBBBBBBB
