BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBB
BBBBB BBBBBBBBBBBBBBBBBBBBBB
   gettext(u'successfully completed all courses and received passing grades for a Professional Certificate in')   FFFFFFFFFFFF
BBBBBBBB
BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
   gettext(u'Professional Certificate')  FFFFFFFFFFFF
BBBBBBBB
BBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB
BBBBB BBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB
BBBBB BBBBBBBBBBBBB
  XX XXXXXXXXXXXX XXXXXXXX
    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXX
BBBBBBBB
