# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-16 09:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180730_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='edly_client_branding_and_django_settings',
            field=jsonfield.fields.JSONField(default={}, help_text='JSON string containing edly client theme branding & Django settings.', verbose_name='Edly client theme branding & Django settings'),
        ),
    ]
