# Generated by Django 4.2.20 on 2025-09-16 11:47

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_core_user_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='edly_client_branding_and_django_settings',
            field=jsonfield.fields.JSONField(default={}, help_text='JSON string containing edly client theme branding & Django settings.', verbose_name='Edly client theme branding & Django settings'),
        ),
    ]
