# Generated by Django 4.2.20 on 2025-10-08 06:04

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_siteconfiguration_edly_client_branding_and_django_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='edx_org_short_name',
            field=models.CharField(help_text='Unique, short string identifier for organization, same as LMS. Please do not use spaces or special characters. Only allowed special characters are period (.), hyphen (-) and underscore (_).', max_length=255, null=True, unique=True, verbose_name='Organization short name'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='edly_client_branding_and_django_settings',
            field=jsonfield.fields.JSONField(default=dict, help_text='JSON string containing edly client theme branding & Django settings.', verbose_name='Edly client theme branding & Django settings'),
        ),
    ]
