# Generated by Django 4.2.20 on 2025-09-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_siteconfiguration_edly_client_branding_and_django_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='edx_org_short_name',
            field=models.CharField(help_text='Unique, short string identifier for organization, same as LMS. Please do not use spaces or special characters. Only allowed special characters are period (.), hyphen (-) and underscore (_).', max_length=255, null=True, unique=True, verbose_name='Organization short name'),
        ),
    ]
