BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBBBBBBBB BBB

BBBBB BBBBBBB
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX
        XXXX
            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                 gettext(u'Hello') X
            XXXX
            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                 gettext(u'Congratulations on completing the %(program_title)s %(program_type)s Program!') SSSSSSSSSSSSSSS SS SSSSSSSSSS SSS SSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSS SSSSSSSS
            XXXX
             #

            FFFF
            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                 gettext(u'Sincerely,<br/>The %(platform_name)s Team') SSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSS SSSS
            XXXX
        XXXXX
    XXXXX
XXXXXXXX
BBBBBBBB
BBBBBBBBBBBBB
