BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB

BBBBB BBBBB
   X BBBBBBB BBBBBBBBB BBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXBB BBBBBBBBBBBBBXXXBBBBXXXBBBBBXX
      XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Skip to main content') XXXX

      BBBBB BBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBB

      BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
        BBBBB BBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Congratulations, %(user_name)s!') 
                      SSSSSSSSSSSSSSSS SSSSSSSSSSSSSS
                    
                  XXXXX

                  XX XXXXXXXXXXXXXXXXXXXXX
                      BBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
                     gettext(u'You worked hard to earn your certificate from %(platform_name)s — share it with colleagues, friends, and family to get the word out about what you mastered in %(program_display_name)s.') 
                      SSS SSSSSS SSSS SS SSSS SSSS SSSSSSSSSSS SSSS SSSSSSSSSSSSSSSSS S SSSSS SS SSSS SSSSSSSSSSS
                      SSSSSSSS SSS SSSSSS SS SSS SSS SSSS SSS SSSSS SSSS SSS SSSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSS
                    
                  XXXX
                XXXXXX
                BBBBBBB BBBBBBBBBBBBBBB
              XXXXXX
            XXXXXX
          XXXXXX
        BBBBBBBB
      BBBBB

      BBBBB BBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBB

      BBBBB BBBBBBBBBBBBBBBBBBBB
      BBBBBBBB

      BBBBB BBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBB
    XXXXXX
  XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
  

  BB BBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X X
            XXXXXXXX FFFFFFFFFFFFFFFFFFX
            XXXXXX XFFFFFFFFXX
            XXXXX XFFFFFFFFX
        XX
    XXXXXXXXX

    
    
    BBBBBBBBBBBBB BBBBBBBBB BBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BBBBB
BBBBBBBB
