BBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBB
BBBB BBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB

BBBBB BBBBBB
  BB BBBBBBBBBBBBB
      BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBB
    BBBB
      BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBB
    BBBBB
BBBBBBBB

BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB BBBBBBBBBBBBBBBBBBBB
          BBBBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB BBBBBBBBBBBBBBB
            BBBBBBBB
          XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Supported by the following organizations')  FFFFFFFFFFFFXXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

              
              BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXXX  gettext(u'logo')   FFFFFFFFFFFFXX
                    XXXXXX
                  XXXXX
              BBBBBB
            XXXXX
          XXXXXX
        XXXXXX
      BBBBBBB


      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            # Translators: This phrase is followed by a statement of the learner's achievement. e.g. 'has completed the course'
             gettext(u'{start_span}This is to certify that{end_span} {start_strong} {user_name} {end_strong}') 
            BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
              BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
              XXXXXXX
            XXXXXXX

            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
              BBBBBB BBBBBBBBBBBB
                # Translators: organization_name is the display name for the provided organization e.g (e.g., Test Organization).
                 gettext(u'a program offered by %(org_name_string)s, in collaboration with %(platform_name)s.') 
                  S SSSSSSS SSSSSSS SS SSSSSSSSSSSSSSSSSSSS SS SSSSSSSSSSSSS SSSS SSSSSSSSSSSSSSSSSS
                
              BBBBBBBBB
            XXXXXXX
          XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Noted by')  FFFFFFFFFFFFXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              BBB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
                BBBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  BBBBBBBBBB BBB
                  XXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXXXX
                  BBBBBBBBBBBBB
                XXXX
              XXXXXX
              BBBBBB
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB BBBBBBBBBBBBB
            BBBBBBBB
          XXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              # Translators: This phrase appears on certificates to show the issue date
               gettext(u'Issued {month} {year}') 
              BBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
               FFFFFFFF
            XXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX gettext(u'Valid Certificate ID')  FFFFFFFFFFFFXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX

          BB BBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX gettext(u'Effort')  FFFFFFFFFFFFXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX
                BBBBBB BBBBBBBBBBBB
                   ngettext(u'%(num_hours)s hour', u'%(num_hours)s hours', count) SSSSSSSSSSSSS SSSSPPPPPPPPPPPPP PPPPP
                BBBBBBBBB
              XXXXXXX
            XXXXX
          BBBBB
        XXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'For tips and tricks on printing your certificate, view the {start_anchor}Web Certificates help documentation{end_anchor}.') 
            SSS SSSS SSS SSSSSS SS SSSSSSSS SSSS SSSSSSSSSSSS SSSS SSS SSSSSSSSSSSSSSSSS SSSSSSSSSSSS SSSS
            SSSSSSSSSSSSSSSSSSSSSSSSSS
          
          BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
        XXXX
      XXXXXX
    XXXXXX
  XXXXXX

  BBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBBBBB
XXXXXXX
BBBBBBB
