# Generated by Django 5.2.7 on 2026-07-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_pathway_status_never_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='certificate_logo_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
