


BBBB BBBB

BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXX XXXXXXFFFFFFFFFFFFX XXXXXFFFFFFFFFFFFFFFX XXXXXXX
    XXXXXXX XX
    XXXXXXXX XX
    XXXXXXXXXX XXXXX
XX
XXXX XXXXXXX XXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXX X XXXX X XXXXX
    XX
        XXXX
            XXXX XXXXXX XXX
            XXX XXXXXXXXXXXXXX XXXXXXX
                XXXXXXXX XXXXX
            XX
                BBBBB BBBBBB
                XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX
                        XXX XXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                                    XXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBB gettext(u'Go to %(platform_name)s Home Page') SS SS SSSSSSSSSSSSSSSSS SSSS SSSSBBBBBBBBBXXXXXXX
                        XXXXX
                    XXXXX
                XXXXXXXX
                BBBBBBBB
            XXXXX
        XXXXX

        XXXX
            XXXX XXXX XXX
            XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXX XXXX XXXXX
                XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXXX
            XX
                BBBBB BBBBBBBBBBBBBBB
            XXXXX
        XXXXX

        XXXX
            XXXX XXXXXX XXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX
                        XXXX XXXXXXXXX XXX
                        XXXX
                            XXXXXX BBB BBB X  gettext(u'All rights reserved')  FFFFFFFFFFFFXXXXXX
                        XXXXX
                    XXXXX
                XXXXXXXX
            XXXXX
        XXXXX
    XXXXXXXX
XXXXXX
